input {
  beats {
    port => 5044
  }
}

filter {

  grok {
    match => {
      "message" => [
        "%{TIMESTAMP_ISO8601:log_timestamp} - %{LOGLEVEL:log.level} - %{GREEDYDATA:message}"
      ]
    }
  }

  date {
    match => [ "log_timestamp", "ISO8601" ]
    target => "@timestamp"
    remove_field => [ "log_timestamp" ]
  }

  mutate {
    add_field => {
      "pipeline" => "centralized-log-pipeline"
    }
  }

}

output {

  elasticsearch {
    hosts => ["http://127.0.0.1:9200"]
    index => "logs-%{+YYYY.MM.dd}"
  }

}
