apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:

  - name: Prometheus

    uid: prometheus

    type: prometheus

    access: proxy

    url: http://127.0.0.1:9090

    isDefault: true

    editable: false

    jsonData:

      httpMethod: POST

      prometheusType: Prometheus

      prometheusVersion: 3.x

      cacheLevel: High

      timeInterval: 15s
