apiVersion: 1

providers:
  - name: Alertmanager Integration
    orgId: 1
    folder: Observability
    type: file
    disableDeletion: false
    editable: false
    updateIntervalSeconds: 30
    options:
      path: /var/lib/grafana/dashboards
